### ISSUE TITLE
Hi, how do you convert jar to exe?

### ISSUE THREAD

**Issue by nkligang** [dustinkredmond/ClipBoardPlusPlus#1]
how do you convert jar to exe?

**Comment by dustinkredmond** [comment]
@nkligang the easiest way is to use launch4j and wrap the JAR in an executable. There are tutorials online for how to do this. It gets a little trickier after Java 8, but so long as JavaFX is on the classpath, I think you'll be okay.

**Comment by nkligang** [comment]
I use exe4j to wrap the jar to an exe. Which tool do you use to make setup package? I use nsis to make, it looks like a bit unprofessional.

**Comment by dustinkredmond** [comment]
@nkligang You may want to look into jpackage that is distributed with the current JDKs.
