### ISSUE TITLE
Is there a way this can be implemented with a list instead of a table ?

### ISSUE THREAD

**Issue by eriksdev1** [dustinkredmond/ClipBoardPlusPlus#3]
Good day, I was just wondering if this can be implemented with a list instead of a table ? I've been learning a lot from studying this project, I'm really thankful to the developer. 

I'm asking this because I was trying to find a way to create the controls with a fxml file instead of programmatically but I was not successful.

Best Regards !

**Comment by dustinkredmond** [comment]
Hi @eriksdev1, yes, it could have also been done with a JavaFX List, though you are able to use TableViews in FXML also, so either way can fit your requirement.
